project:
  type: book
  output-dir: _book
book:
  title: "Buku Contoh"
  author: "Nama Penulis"
  chapters:
    - index.qmd
    - daftar-ilustrasi.qmd
    - part: "Dasar"
      chapters:
        - dasar.qmd
    - part: "Praktik"
      chapters:
        - praktik.qmd
    - lampiran.qmd
    - referensi.qmd
bibliography: references.bib
format:
  min-book-quarto-typst:
    papersize: a5 # Ganti, misalnya menjadi iso-b5 atau us-letter.
    keep-typ: true
    include-in-header:
      - file: catalog.typ
      - text: |
          #import "layout.typ" as example-theme
          #let min-book-config = (theme: example-theme)
          #set bibliography(title: none)
lang: id
min-book:
  parts: true
  two-sided: true
  paper-friendly: false
  publication-date: "2026-09-19"
